import { StoryBlokComponent, ImageLink } from ".";
import { ProductSkuComponent } from "./ProductSkuComponent";
export interface ProductComponent extends StoryBlokComponent<"product"> {
    name:               string;
    image:              ImageLink;
    highlights:         string;
    description:        string;
    benefits:           any;
    content:            any;
    priority:           number;
    related:            any;
    data:               string;
    id:                 string;
    legacy_ids:         string;
    tagline:            string;
    legacy_description: string;
    images_pim:         any[];
    category:           string;
    position:           string;
    position_pim:       number;
    importance:         number;
    product_range:      string;
    attributes:         any;
    certificates:       string;
    last_update:        string;
    items:              ProductSkuComponent[] | undefined;
    inserts:            any;
    sku_options:        any;
    deleted:            boolean;
}