// Generated by https://quicktype.io

export interface WorkflowStateChange {
    id:                number;
    workflow_stage_id: number;
    created_at:        string;
    user_id:           number;
}

// Generated by https://quicktype.io

export interface WorkflowStage {
    allow_publish:       boolean;
    is_default:          boolean;
    id:                  number;
    user_ids:            any[];
    space_role_ids:      any[];
    workflow_stage_ids:  any[];
    name:                string;
    color:               string;
    allow_all_stages:    boolean;
    allow_admin_publish: boolean;
    allow_all_users:     boolean;
    position:            number;
    after_publish_id:    null;
}
